line-length = 80
indent-width = 4
target-version = "py311"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = ["E", "W", "F", "I", "B", "N", "UP", "C90", "D", "RUF", "SIM", "ANN", "PTH", "ERA"]
ignore = ["D100", "D104", "D107", "ANN101", "ANN102", "ANN401"]
fixable = ["ALL"]

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10

[lint.isort]
combine-as-imports = true
